defaults:
  - _self_

model:
  name: "gpt2"
  max_length: 128
  batch_size: 32
  learning_rate: 2e-5
  num_epochs: 3
  
data:
  train_file: "data/train.txt"
  val_file: "data/val.txt"
  test_file: "data/test.txt"
  
training:
  seed: 42
  device: "cuda"
  gradient_accumulation_steps: 1
  warmup_steps: 0
  logging_steps: 100
  eval_steps: 500
  save_steps: 1000
  
output:
  save_dir: "outputs"
  model_name: "model.pt"
  log_file: "training.log"
